name: Auto Update Youtube video id

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment: prod
    env:
      YOU_TUBE_API_KEY: ${{secrets.YOU_TUBE_API_KEY}}
      GH_ACCESS_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
    steps:
      - name: Verify environment
        run: |
          echo "Environment variable YOU_TUBE_API_KEY: $YOU_TUBE_API_KEY "
          echo "Environment variable GH_ACCESS_TOKEN: $GH_ACCESS_TOKEN"
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to update video_meta.json to scraper
        run: |
          # Add your script execution command here
          python main.py
